apiVersion: v2
name: amazon-clone
description: A Helm chart for Amazon Clone application
type: application
version: 0.1.0
appVersion: "1.0.0"

# Dependencies for the chart
dependencies:
  - name: mysql
    version: 9.15.0
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: nginx
    version: 15.3.1
    repository: https://charts.bitnami.com/bitnami
    condition: nginx.enabled
  - name: prometheus
    version: 25.13.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 7.1.1
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
